# FOR LOCAL TESTING ONLY
version: '3.9'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  app:
    build: .
    restart: always
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - '3000:3000'
    environment:
      - DB_URL=mongodb://root:password@mongodb:27017/?retryWrites=true&w=majority
volumes:
  mongodb_data:
